# Vectors dipolar moments in aggregates

In [1]:
import mdtraj as md
import nglview as nv
import numpy as np
import os
from scipy.constants import e

In [2]:
os.chdir("/run/media/ovillegas/My Passport/LAPTOP Oblivion/ovillegas/Documents/PYRENE_backup/exp.asp.sol")

In [3]:
os.chdir("aggregate_solvent/A12.THF/80/md/clusters_info")

In [9]:
# my params
config = {'type': 'ball+stick',
 'params': {'lazy': False,
  'visible': True,
  'quality': 'high',
  'sphereDetail': 2,
  'radialSegments': 20,
  'openEnded': True,
  'disableImpostor': False,
  'aspectRatio': 1.5,
  'lineOnly': False,
  'cylinderOnly': False,
  'multipleBond': 'off',
  'bondScale': 0.3,
  'bondSpacing': 0.75,
  'linewidth': 2,
  'radiusType': 'size',
  'radiusData': {},
  'radiusSize': 0.15,
  'radiusScale': 2,
  'assembly': 'default',
  'defaultAssembly': '',
  'clipNear': 0,
  'clipRadius': 0,
  'clipCenter': {'x': 0, 'y': 0, 'z': 0},
  'flatShaded': False,
  'opacity': 0.4,
  'depthWrite': True,
  'side': 'double',
  'wireframe': False,
  'colorScheme': 'element',
  'colorScale': '',
  'colorReverse': False,
  'colorValue': 9474192,
  'colorMode': 'hcl',
  'roughness': 0.4,
  'metalness': 0,
  'diffuse': 16777215,
  'diffuseInterior': False,
  'useInteriorColor': True,
  'interiorColor': 2236962,
  'interiorDarkening': 0,
  'matrix': {'elements': [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1]},
  'disablePicking': False,
  'sele': ''}}

In [20]:
def dipolar_momentum(coord, charges, n=1):
    mu_xyz = (coord.T * charges).T * (4.8 / 1.6e-29) * e * 1e-9
    mu_xyz = np.sum(mu_xyz, axis=0) / n
    return mu_xyz

def show_gro(file, n=1, vec=True):
    traj = md.load(file, top=file)
    
    t = nv.MDTrajTrajectory(traj)
    w = nv.NGLWidget(t)
    w.update_representation(opacity=0.4)
    if vec:
        if n > 1:
            w.representations = [config]
            top = traj.topology
            atomsndx = top.select("resname A12")
            atomstot = int(len(top.select("resname A12")) / n)
        
            for i in range(n):
                mol = atomsndx[0+i*atomstot:atomstot+i*atomstot]
                tmol = traj.atom_slice(mol)
            
                cm = md.compute_center_of_mass(tmol)[0] * 10
                vec_dipol = dipolar_momentum(tmol.xyz[0], charges) + cm
        
                w.shape.add_sphere(cm, [0.36078431, 0.72156863, 0.36078431], 1.0)
                w.shape.add_arrow(cm, vec_dipol, [0, 0.4, 0.8], 0.5)
                
        elif n == 1:
            cm = md.compute_center_of_mass(traj)[0] * 10
            vec_dipol = dipolar_momentum(traj.xyz[0], charges) + cm
            w.shape.add_sphere(cm, [0.36078431, 0.72156863, 0.36078431], 1.0)
            w.shape.add_arrow(cm, vec_dipol, [0, 0.4, 0.8], 0.5)
    
    return w

def get_file(n):
    for i in os.listdir():
        if i.endswith(".gro"):
            aggiframe, nmol, _ = i.split("_")
            if int(nmol) == n:
                print(i)

In [13]:
charges = np.genfromtxt("../../a12.itp", skip_header=17, skip_footer=340)[:, 6]

In [14]:
w = show_gro("aggr2270_1_150.gro")

In [15]:
w

NGLWidget()

In [16]:
show_gro("aggr210_1_20.gro", n=1, vec=True)

NGLWidget()

In [187]:
get_file(5)

aggr2410_5_153.gro
aggr2145_5_145.gro


In [21]:
w = show_gro("aggr2410_5_153.gro", n=5, vec=True)

In [22]:
w

NGLWidget()

In [11]:
# w.get_state()

In [209]:
w.update_representation(opacity=0.4, component=1)

In [204]:
w.download_image("a12_5mol_mu.png", factor=8, antialias=True, transparent=True)

In [115]:
w.download_image("a12_1mol_mu.png", factor=8, antialias=True, transparent=True)

In [173]:
w = show_gro("aggr2410_5_153.gro", n=5, vec=False)
w.update_representation(opacity=0.4)

In [179]:
w.update_representation(repr_type="ball+stick", selection='resname A12', opacity=0.3)

In [181]:
w.picked

{}

In [108]:
np.array([92,184,92]) / 255

array([0.36078431, 0.72156863, 0.36078431])

In [44]:
w.shape.add_sphere?

Signature: w.shape.add_sphere(*args)
Docstring:
# add_sphere(position, color, radius, name)
>>> shape.add_sphere([0, 0, 9], [1, 0, 0], 1.5)
File:      ~/anaconda3/envs/SimMOL/lib/python3.9/site-packages/nglview/shape.py
Type:      method


In [79]:
charges = np.genfromtxt("../../a12.itp", skip_header=17, skip_footer=340)[:, 6]

In [83]:
charges

array([ 0.   ,  0.   , -0.14 ,  0.177, -0.635,  0.386,  0.14 ,  0.14 ,
        0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   , -0.14 ,
        0.   ,  0.   ,  0.14 ,  0.068,  0.   ,  0.   ,  0.   , -0.136,
        0.   ,  0.   ,  0.   ,  0.   , -0.14 ,  0.   ,  0.   ,  0.075,
        0.   ,  0.14 , -0.495,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
        0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
        0.   ,  0.42 ])

In [94]:
dipolar_momentum(t.xyz[0], charges)

array([-3.04748447, -1.8411873 ,  4.48824558])

In [190]:
t = md.load('aggr2270_1_150.gro', top='aggr2270_1_150.gro')

In [34]:
top = t.topology

In [35]:
table, bonds = top.to_dataframe()

In [50]:
md.compute_center_of_mass(t)[0]

array([9.24469894, 1.06756786, 9.52172216])

In [6]:
# aggr2270_1_150.gro
# aggr2410_5_153.gro
t = md.load('aggr2410_5_153.gro', top='aggr2410_5_153.gro')
t = nv.MDTrajTrajectory(t)
w = nv.NGLWidget(t, gui=False)

In [7]:
w

NGLWidget()

In [8]:
w.representations = [config]

In [331]:
# w.update_representation(opacity=0.4)

In [311]:
#w.update_representation(component=1, opacity=0.4)
# w.remove_cartoon()
#w.remove_ball_and_stick()

In [291]:
# w.get_state()['_ngl_msg_archive']

In [336]:
w.representations = [
{'type': 'ball+stick',
 'params': {'lazy': False,
  'visible': True,
  'quality': 'high',
  'sphereDetail': 2,
  'radialSegments': 20,
  'openEnded': True,
  'disableImpostor': False,
  'aspectRatio': 1.5,
  'lineOnly': False,
  'cylinderOnly': False,
  'multipleBond': 'off',
  'bondScale': 0.3,
  'bondSpacing': 0.75,
  'linewidth': 2,
  'radiusType': 'size',
  'radiusData': {},
  'radiusSize': 0.15,
  'radiusScale': 2,
  'assembly': 'default',
  'defaultAssembly': '',
  'clipNear': 0,
  'clipRadius': 0,
  'clipCenter': {'x': 0, 'y': 0, 'z': 0},
  'flatShaded': False,
  'opacity': 0.4,
  'depthWrite': True,
  'side': 'double',
  'wireframe': False,
  'colorScheme': 'element',
  'colorScale': '',
  'colorReverse': False,
  'colorValue': 9474192,
  'colorMode': 'hcl',
  'roughness': 0.4,
  'metalness': 0,
  'diffuse': 16777215,
  'diffuseInterior': False,
  'useInteriorColor': True,
  'interiorColor': 2236962,
  'interiorDarkening': 0,
  'matrix': {'elements': [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1]},
  'disablePicking': False,
  'sele': ''}}
]

In [324]:
w.representations = [
    {"type": 'ball+stick',
     "params" : {
         "opacity": 0.4
     }}
]

In [332]:
w.get_state()['_ngl_repr_dict']['0']['0']

{'type': 'ball+stick',
 'params': {'lazy': False,
  'visible': True,
  'quality': 'high',
  'sphereDetail': 2,
  'radialSegments': 20,
  'openEnded': True,
  'disableImpostor': False,
  'aspectRatio': 1.5,
  'lineOnly': False,
  'cylinderOnly': False,
  'multipleBond': 'off',
  'bondScale': 0.3,
  'bondSpacing': 0.75,
  'linewidth': 2,
  'radiusType': 'size',
  'radiusData': {},
  'radiusSize': 0.15,
  'radiusScale': 2,
  'assembly': 'default',
  'defaultAssembly': '',
  'clipNear': 0,
  'clipRadius': 0,
  'clipCenter': {'x': 0, 'y': 0, 'z': 0},
  'flatShaded': False,
  'opacity': 0.4,
  'depthWrite': True,
  'side': 'double',
  'wireframe': False,
  'colorScheme': 'element',
  'colorScale': '',
  'colorReverse': False,
  'colorValue': 9474192,
  'colorMode': 'hcl',
  'roughness': 0.4,
  'metalness': 0,
  'diffuse': 16777215,
  'diffuseInterior': False,
  'useInteriorColor': True,
  'interiorColor': 2236962,
  'interiorDarkening': 0,
  'matrix': {'elements': [1, 0, 0, 0, 0, 1, 0, 0, 0,

In [317]:
w.get_state()['_ngl_repr_dict']

{'0': {'0': {'type': 'cartoon',
   'params': {'lazy': False,
    'visible': True,
    'quality': 'high',
    'aspectRatio': 5,
    'subdiv': 6,
    'radialSegments': 20,
    'tension': None,
    'capped': True,
    'smoothSheet': False,
    'radiusType': 'sstruc',
    'radiusData': {},
    'radiusSize': 1,
    'radiusScale': 0.7,
    'assembly': 'default',
    'defaultAssembly': '',
    'clipNear': 0,
    'clipRadius': 0,
    'clipCenter': {'x': 0, 'y': 0, 'z': 0},
    'flatShaded': False,
    'opacity': 1,
    'depthWrite': True,
    'side': 'double',
    'wireframe': False,
    'colorScheme': 'residueindex',
    'colorScale': 'spectral',
    'colorReverse': True,
    'colorValue': 9474192,
    'colorMode': 'hcl',
    'roughness': 0.4,
    'metalness': 0,
    'diffuse': 16777215,
    'diffuseInterior': False,
    'useInteriorColor': True,
    'interiorColor': 2236962,
    'interiorDarkening': 0,
    'matrix': {'elements': [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1]},
    'disable

In [286]:
w.get_state()['_ngl_repr_dict']['0']['0']['type']

'cartoon'

In [287]:
w.get_state()['_ngl_repr_dict']['0']['0']['params']['opacity']

1

In [263]:
w = nv.NGLWidget()
w

NGLWidget()

In [264]:
w.add_component(t, opacity)

In [228]:
w.n_components

1

In [230]:
w.update_representation(component=0, opacity=0.4)

In [ ]:
def show_gro(file):
    t = md.load(file, top=file)
    t = nv.MDTrajTrajectory(t)
    w = nv.NGLWidget(t)
    return w